# Generated by Django 3.2.4 on 2021-08-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gencal', '0002_auto_20210819_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='GemItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
