# Generated by Django 3.2.4 on 2021-08-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gencal', '0003_gemitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(choices=[('0', 'Anemo'), ('1', 'Cryo'), ('2', 'Dendro'), ('3', 'Electro'), ('4', 'Geo'), ('5', 'Hydro'), ('6', 'Pyro'), ('7', 'Traveler')], max_length=1),
        ),
    ]
