# Generated by Django 3.2.4 on 2021-08-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gencal', '0004_alter_element_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='ascension_gem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_gems', to='gencal.gemitem'),
        ),
    ]
