# Generated by Django 3.2.4 on 2021-08-24 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gencal', '0005_alter_character_ascension_gem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('0', 'No Stars'), ('1', '1 Star'), ('2', '2 Stars'), ('3', '3 Stars'), ('4', '4 Stars'), ('5', '5 Stars')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'Bow'), ('1', 'Catalyst'), ('2', 'Claymore'), ('3', 'Polearm'), ('4', 'Sword')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='weapon',
            name='rarity',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='weapons_by_rarity', to='gencal.starrating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='weapons_by_type', to='gencal.weapontype'),
            preserve_default=False,
        ),
    ]
